apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "envVarChart.name" . }}
  labels:
    {{- include "envVarChart.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "envVarChart.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "envVarChart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "envVarChart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.pod.port }}
          env:
            - name: ENV_VAR
              value: "I'm an environment variable"
            - name: TEST_API
              value: "Just testing the api"