# Default values for envVarChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: michalhope1/env-vars
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.2"

nameOverride: "env-vars-app"

pod:
  port: 5000

service:
  type: ClusterIP
  port: 5000
  protocol: TCP

serviceName: "microservice"